# Datasource configuration

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_test
    username: lexz
    password: 1973461997$
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    